theme: jekyll-theme-dinky
title: [Alumkal Lab R-Workshop]
description: [Learning how to Use R for Common Data Manipulations]
repository: AlumkalLab/AlumkalLab.github.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
